# Test HTTP requests rest rajapinta
### use with: REST CLIENT extension

### GET all items @ merkki tarvitaan localhost muuttujan eteen
@apiurl = http://localhost:3000/api
GET {{apiurl}}/items

### ADD NEW item.  Eka serveri, millänen contentin tyyppi ja alle tieto
POST {{apiurl}}/items
Content-Type: application/json

{"name": "Mandariini"}

### UPDATE item with id 1. Muuta nimen Appelsiiniksi

PUT {{apiurl}}/items/1
Content-Type: application/json

{"name": "Appelsiini"}

### DELETE item 
DELETE {{apiurl}}/items/1

##########################################################################################
### GET all users
GET {{apiurl}}/users
###Register new user
POST {{apiurl}}/users
Content-Type: application/json

  {
    
    "username": "Make",
    "password": "Makkonen",
    "email": "makeke@example.com"
  }

###
GET {{apiurl}}/users




###Register new user FAILED (missing email)


###login user
POST {{apiurl}}/users/login
Content-Type: application/json

  {
    
    "username": "Make",
    "password": "Makkonen"
    
  }

#################################
### Get user by id 3
GET {{apiurl}}/users/3
Content-Type: application/json

##### Update email of user id 3
PUT {{apiurl}}/users/3
content-type: application/json


{
  "email": "vaihdettuid3@metropolia.fi"
}


###### User delete by id 2

DELETE {{apiurl}}/users/2

#######################