# Test HTTP requests
### use with: REST CLIENT extension

### GET all items

GET http://localhost:3000/items

### ADD NEW item.  Eka serveri, millänen contentin tyyppi ja alle tieto
POST http://localhost:3000/items
Content-Type: application/json

{"name": "Mandariini"}

### UPDATE item with id 1. Muuta nimen Appelsiiniksi

PUT http://localhost:3000/items/1
Content-Type: application/json

{"name": "Appelsiini"}

### DELETE item 
DELETE http://localhost:3000/items/1
