# Test HTTP requests rest rajapinta
### use with: REST CLIENT extension

### GET all items @ merkki tarvitaan localhost muuttujan eteen
@apiurl = http://localhost:3000/api
GET {{apiurl}}/items

### ADD NEW item.  Eka serveri, millänen contentin tyyppi ja alle tieto
POST {{apiurl}}/items
Content-Type: application/json

{"name": "Mandariini"}

### UPDATE item with id 1. Muuta nimen Appelsiiniksi

PUT {{apiurl}}/items/1
Content-Type: application/json

{"name": "Appelsiini"}

### DELETE item 
DELETE {{apiurl}}/items/1
